"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['get_version.py']  # 替换为你实际的脚本文件名，去掉 .py 后缀
DATA_FILES = []  # 如果有额外的文件（例如：test.md、version.png），可以放在这里
OPTIONS = {
    'argv_emulation': True,  # 如果需要命令行参数支持，启用此选项
    'packages': ['requests', 'pandas', 'matplotlib'],  # 确保依赖项包括在应用中
    'includes': ['pathlib'],  # 如果有其他模块，确保它们也被包括
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
